# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\x12\x08transfer\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"!\n\x10\x44ownloadResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"0\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\"-\n\x0eUploadResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x91\x01\n\x0b\x46ileService\x12\x43\n\x08\x44ownload\x12\x19.transfer.DownloadRequest\x1a\x1a.transfer.DownloadResponse0\x01\x12=\n\x06Upload\x12\x17.transfer.UploadRequest\x1a\x18.transfer.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=28
  _globals['_DOWNLOADREQUEST']._serialized_end=63
  _globals['_DOWNLOADRESPONSE']._serialized_start=65
  _globals['_DOWNLOADRESPONSE']._serialized_end=98
  _globals['_UPLOADREQUEST']._serialized_start=100
  _globals['_UPLOADREQUEST']._serialized_end=148
  _globals['_UPLOADRESPONSE']._serialized_start=150
  _globals['_UPLOADRESPONSE']._serialized_end=195
  _globals['_FILESERVICE']._serialized_start=198
  _globals['_FILESERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
