FROM python:3.11-slim

WORKDIR /app
COPY src/peer /app
RUN pip install --no-cache-dir -r /app/../requirements.txt

# compile protos (optional if precompiled)
# If using dynamic compile:
RUN python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. proto/transfer.proto

EXPOSE 8000 50051

CMD ["python", "main.py", "--config", "/config/config.json"]
